### ISSUE TITLE
NetworkGammaEnt: System.MissingMethodException: Method not found

### ISSUE THREAD

**Issue by JoeMcNuggets** [jellyfin-adult/Jellyfin.Plugin.PhoenixAdultRebirth#121]
**Describe the bug**
At almost every video for provider Pronium.Sites.NetworkGammaEnt this error occurs

**Include**
Jellyfin or Emby
10.10.10
Plugin Version
2.1.5.94
Logs

```
System.MissingMethodException: Method not found: 'System.String MediaBrowser.Controller.Entities.PersonInfo.get_Type()'.
   at Pronium.Helpers.Actors.Cleanup(MetadataResult`1 scene)
   at Pronium.Providers.MovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

**Comment by jellyfin-adult** [comment]
Thanks for reporting, I'll investigate.

**Comment by jellyfin-adult** [comment]
It looks like it's related to Jellyfin new version 10.10. I'll try to update dependencies and fix this issue.

https://github.com/jellyfin/jellyfin/pull/9487

**Comment by jellyfin-adult** [comment]
@JoeMcNuggets please, check the latest version, I've added a new release to the manifest
