### ISSUE TITLE
plugin not working or not load

### ISSUE THREAD

**Issue by koko009** [jellyfin-adult/Jellyfin.Plugin.PhoenixAdultRebirth#34]
i have emby server v4.8 
and i want install this plugin 
iam copy this plugin in folder plugin and restart my server 
but not load 
i dont see any new plugin 

plugin v2.0.1.54
emby v4.8 on synology nas

**Comment by jellyfin-adult** [comment]
@koko009 Could you, please, provide logs from Emby? I have the same setup: Synology, Emby 4.8.1.0, and v2.0.1.54, and the plugin is loading and working.

**Comment by koko009** [comment]
@jellyfin-adult 
2024-02-20 01:53:27.718 Error App: Error loading assembly /var/packages/EmbyServer/var/plugins/Emby.Plugins.Pronium.dll
	*** Error Report ***
	Version: 4.8.1.0
	Command line: /volume1/@appstore/EmbyServer/system/EmbyServer.dll -programdata /var/packages/EmbyServer/var -ffdetect /var/packages/EmbyServer/target/bin/ffdetect -ffmpeg /var/packages/EmbyServer/target/bin/ffmpeg -ffprobe /var/packages/EmbyServer/target/bin/ffprobe -nolocalportconfig -ignore_vaapi_enabled_flag -pidfile /var/packages/EmbyServer/var/EmbyServer.pid -defaultdirectory /volume1/Public -updatepackage emby-server-synology72_{version}_x86_64.spk -noautorunwebapp
	Operating system: Linux version 4.4.302+ (root@build8) (gcc version 12.2.0 (GCC) ) #69057 SMP Fri Jan 12 17:02:26 CST 2024
	Framework: .NET 6.0.25
	OS/Process: x64/x64
	Runtime: volume1/@appstore/EmbyServer/system/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /var/packages/EmbyServer/var
	Application path: /volume1/@appstore/EmbyServer/system
	System.UnauthorizedAccessException: System.UnauthorizedAccessException: Access to the path '/var/packages/EmbyServer/var/plugins/Emby.Plugins.Pronium.dll' is denied.
	 ---> System.IO.IOException: Permission denied
	   --- End of inner exception stack trace ---
	   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
	   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
	   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
	   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
	   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
	   at System.IO.File.ReadAllBytes(String path)
	   at Emby.Server.Implementations.ApplicationHost.LoadAssembly(String file)
	Source: System.Private.CoreLib
	TargetSite: Void ThrowExceptionForIoErrno(ErrorInfo, System.String, Boolean, System.Func`2[Interop+ErrorInfo,Interop+ErrorInfo])
	InnerException: System.IO.IOException: Permission denied
	Source: 
	TargetSite:

**Comment by jellyfin-adult** [comment]
It's not about the plugin. It's about permissions. When you've copied plugin to the Emby directory you did it with your account and Emby is trying to access it with an internal system account. If you did it using SSH something like this should resolve your issue:

```
chmod 777 /volume1/@appdata/EmbyServer/plugins/Emby.Plugins.Pronium.dll
```

Basically, this command will grant permissions to all users on Synology.

**Comment by koko009** [comment]
thanks 
now is working but i dont know how to use

**Comment by agorbikov-capital** [comment]
@koko009 it's very similar to any other metadata provider: you create a library and add this plugin as a metadata provider.

**Comment by jellyfin-adult** [comment]
@koko009 it should be pretty simple, you create a library and add this plugin as a metadata provider.
