### ISSUE TITLE
`pornDB` integration fails to update metadata

### ISSUE THREAD

**Issue by jellyfin-adult** [jellyfin-adult/Jellyfin.Plugin.PhoenixAdultRebirth#79]
```
2024-06-01 11:49:55.262 Error Pronium: Update error: "System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Pronium.Sites.Network1service.Update(Int32[] siteNum, String[] sceneID, CancellationToken cancellationToken)
   at Pronium.Providers.MovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)"
2024-06-01 11:49:55.263 Error Pronium: GetImages error: "System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Pronium.Sites.Network1service.GetImages(Int32[] siteNum, String[] sceneID, BaseItem item, CancellationToken cancellationToken)
   at Pronium.Providers.MovieImageProvider.GetImages(BaseItem item, LibraryOptions libraryOptions, CancellationToken cancellationToken)"
```

**Comment by jellyfin-adult** [comment]
Fixed in #80
