### ISSUE TITLE
`data18` is not working in some scenarios

### ISSUE THREAD

**Issue by jellyfin-adult** [jellyfin-adult/Jellyfin.Plugin.PhoenixAdultRebirth#99]
**Describe the bug**
`data18` is not working in some scenarios

**Include**
1. Emby
2. Latest
3. [Scene URL](https://www.data18.com/scenes/144862)
4. `data18 - Block Out Your Husband.mp4`
5. Log File

```zsh
2024-06-22 19:33:21.367 Error Pronium: Update error: "System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at Pronium.Sites.SiteData18.Update(Int32[] siteNum, String[] sceneID, CancellationToken cancellationToken)
   at Pronium.Providers.MovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)"
```

**Comment by jellyfin-adult** [comment]
Fixed in #100
